name: iic_radio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - "assets/"
  fonts: 
    - family: sans-regular
      fonts: 
        - asset: assets/GoogleSans-Regular.ttf
    - family: sans-bold
      fonts: 
        - asset: assets/GoogleSans-Bold.ttf


