name: iic_radio
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.2.1
  radio_player: ^1.6.0
  lottie: ^3.1.2
  dio: ^5.0.0
  just_audio: ^0.9.21
  path_provider: ^2.0.9
  flutter_downloader: ^1.7.1
  
  # firebase_core:
  flutter: 
    sdk: flutter
  animated_text_kit: ^4.2.2
  http: ^1.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - "assets/"
  fonts: 
    - family: sans-regular
      fonts: 
        - asset: assets/GoogleSans-Regular.ttf
    - family: sans-bold
      fonts: 
        - asset: assets/GoogleSans-Bold.ttf
    - family: gotham
      fonts: 
        - asset: assets/GothamBold.ttf


