// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAeAYZctclGgakdywOTKcRRhF_RMkutWnQ',
//     appId: '1:3767420394:web:56af79e5ea3a5b64d85e93',
//     messagingSenderId: '3767420394',
//     projectId: 'iicradio',
//     authDomain: 'iicradio.firebaseapp.com',
//     storageBucket: 'iicradio.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCNG-b0z6-li2eo_3ObZScDh2ReUOhSgxc',
//     appId: '1:3767420394:android:28fdba02c3f5850fd85e93',
//     messagingSenderId: '3767420394',
//     projectId: 'iicradio',
//     storageBucket: 'iicradio.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDQAiQuVvwKVCaZu4nl7YXkC46UkmCrLh0',
//     appId: '1:3767420394:ios:088006a83ba61decd85e93',
//     messagingSenderId: '3767420394',
//     projectId: 'iicradio',
//     storageBucket: 'iicradio.appspot.com',
//     iosBundleId: 'com.example.iicRadio',
//   );
// }
